name: miniflutt
description: Another Miniflux client.

version: 1.16.0+2726755 # Commit 47b8557b
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.4.0
  flutter_html: ^3.0.0
  flutter_html_audio: ^3.0.0
  flutter_html_iframe: ^3.0.0
  flutter_html_svg: ^3.0.0
  flutter_html_table: ^3.0.0
  flutter_html_video: ^3.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  provider: ^6.1.5
  scrollable_positioned_list: ^0.3.8
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
